// <auto-generated />
using EmployeeManagement_ASP.Net_Core_MVC_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeManagement_ASP.Net_Core_MVC_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210129231846_AlterSeedData2")]
    partial class AlterSeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeManagement_ASP.Net_Core_MVC_Project.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Department");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "one@one.org",
                            Name = "Vivek Arya"
                        },
                        new
                        {
                            Id = 2,
                            Department = 2,
                            Email = "two@one.org",
                            Name = "Vivek Sharma"
                        },
                        new
                        {
                            Id = 3,
                            Department = 2,
                            Email = "three@one.org",
                            Name = "Vimal Mehta"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
